"use client";
import React, { useEffect, useState, useRef } from "react";
import { motion } from "framer-motion";
import PaperFormat from "@/components/papers/PaperFormat";
import SafeMath from "@/components/SafeMath";
import { QuestionPaper } from "@/types/global";

// "full-syllabus-test" and "chapter-test" aren't in the mock JSON yet — added
// now so filtering by nav section already works once real data/API exists.
export type RecentItemType =
  | "sample-paper"
  | "subject-test"
  | "full-syllabus-test"
  | "chapter-test";

interface RecentItem {
  _id: string;
  type: RecentItemType;
  class: string;
  subject: string;
  exam_type: string;
  paperType: string;
  paperJson?: QuestionPaper;
  questions?: any[];
}

const ChevronLeft = () => (
  <svg
    className="w-5 h-5"
    fill="none"
    stroke="currentColor"
    strokeWidth="2.5"
    viewBox="0 0 24 24"
  >
    <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
  </svg>
);

const ChevronRight = () => (
  <svg
    className="w-5 h-5"
    fill="none"
    stroke="currentColor"
    strokeWidth="2.5"
    viewBox="0 0 24 24"
  >
    <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
  </svg>
);

const SCROLL_AMOUNT = 340;

// Shared width classes so skeleton / empty state / real cards always match
// and never exceed the viewport on small screens.
const CARD_WIDTH_CLASSES =
  "w-[85vw] xs:w-[320px] sm:w-[380px] max-w-[380px] shrink-0";

interface ShowcaseProps {
  /** Only show items of this type. Omit (or pass "all") to show everything — current default/explore behavior. */
  filterType?: RecentItemType | "all";
  title?: string;
  description?: string;
}

const Showcase = ({
  filterType = "all",
  title = "RECENT GENERATED",
  description = "These papers and tests are generated by our students and teachers",
}: ShowcaseProps) => {
  const [recentItems, setRecentItems] = useState<RecentItem[]>([]);
  const [loading, setLoading] = useState(true);
  const scrollRef = useRef<HTMLDivElement>(null);
  const [canScrollLeft, setCanScrollLeft] = useState(false);
  const [canScrollRight, setCanScrollRight] = useState(true);

  const checkScroll = () => {
    const el = scrollRef.current;
    if (!el) return;
    setCanScrollLeft(el.scrollLeft > 4);
    setCanScrollRight(el.scrollLeft + el.clientWidth < el.scrollWidth - 4);
  };

  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    checkScroll();
    el.addEventListener("scroll", checkScroll, { passive: true });
    const resizeObs = new ResizeObserver(checkScroll);
    resizeObs.observe(el);
    return () => {
      el.removeEventListener("scroll", checkScroll);
      resizeObs.disconnect();
    };
  }, [recentItems]);

  useEffect(() => {
    let cancelled = false;

    const loadData = async () => {
      setLoading(true);
      try {
        const [sampleRes, testRes] = await Promise.all([
          fetch("/json/sample-paper.json"),
          fetch("/json/subject-test.json"),
        ]);

        const sampleData = sampleRes.ok ? await sampleRes.json() : null;
        const testData = testRes.ok ? await testRes.json() : null;

        if (cancelled) return;

        const items: RecentItem[] = [];

        if (sampleData) {
          [1, 2, 3].map(() => {
            items.push({
              _id: sampleData._id?.$oid || "sample-paper",
              type: "sample-paper",
              class: sampleData.class,
              subject: sampleData.subject,
              exam_type: sampleData.exam_type,
              paperType: sampleData.paperType,
              paperJson: sampleData.paperJson
                ? typeof sampleData.paperJson === "string"
                  ? JSON.parse(sampleData.paperJson)
                  : sampleData.paperJson
                : undefined,
            });
          });
        }

        if (testData) {
          const parsed = testData.paperJson
            ? typeof testData.paperJson === "string"
              ? JSON.parse(testData.paperJson)
              : testData.paperJson
            : {};

          items.push({
            _id: testData._id?.$oid || "subject-test",
            type: "subject-test",
            class: testData.class,
            subject: testData.subject,
            exam_type: testData.exam_type,
            paperType: testData.paperType,
            questions: parsed.questions || [],
            paperJson: {
              title: parsed.title || "Subject Test",
              class: testData.class,
              subject: testData.subject,
              durationMinutes: parsed.durationMinutes || 60,
              totalMarks: parsed.totalMarks || 20,
              instructions: parsed.instructions || [],
              mcqs: parsed.mcqs || [],
              subjective: parsed.subjective || [],
            },
          });
        }

        setRecentItems(
          filterType === "all"
            ? items
            : items.filter((i) => i.type === filterType),
        );
      } catch (err) {
        console.error("Error loading showcase data:", err);
        if (!cancelled) setRecentItems([]);
      } finally {
        if (!cancelled) setLoading(false);
      }
    };

    loadData();

    return () => {
      cancelled = true;
    };
  }, [filterType]);

  const scroll = (dir: "left" | "right") => {
    scrollRef.current?.scrollBy({
      left: dir === "left" ? -SCROLL_AMOUNT : SCROLL_AMOUNT,
      behavior: "smooth",
    });
  };

  const renderSamplePaperPreview = (item: RecentItem) => {
    if (!item.paperJson) return null;
    try {
      return (
        <div className="px-2 !text-sm overflow-x-hidden">
          <PaperFormat data={item.paperJson} />
        </div>
      );
    } catch (err) {
      console.error("PaperFormat render error:", err);
      return (
        <div className="p-4 text-xs text-slate-400">
          Unable to render paper preview.
        </div>
      );
    }
  };

  const renderSubjectTestPreview = (item: RecentItem) => (
    <div className="p-3 sm:p-4 space-y-3 max-h-full overflow-y-auto overflow-x-hidden thin-scroll">
      {item.questions?.map((q: any, idx: number) => (
        <div
          key={q.id || idx}
          className="border border-slate-200 rounded-lg p-3 min-w-0"
        >
          <div className="flex items-start justify-between gap-2 mb-1 flex-wrap">
            <span className="font-bold text-slate-700 text-xs min-w-5">
              {idx + 1}.
            </span>
            <span
              className={`text-[10px] font-extrabold px-1.5 py-0.5 rounded-full uppercase shrink-0 ${
                q.type === "mcq"
                  ? "bg-blue-50 text-blue-600"
                  : q.type === "subjective"
                    ? "bg-purple-50 text-purple-600"
                    : q.type === "case" || q.type === "caseStudy"
                      ? "bg-orange-50 text-orange-600"
                      : "bg-slate-50 text-slate-600"
              }`}
            >
              {q.type || "mcq"}
            </span>
          </div>
          <div className="flex items-start gap-2 min-w-0">
            <div className="flex-1 min-w-0">
              <div className="text-xs text-slate-800 font-medium mb-1.5 break-words">
                <SafeMath>{q.question}</SafeMath>
              </div>
              {q.options && (
                <div className="grid grid-cols-1 xs:grid-cols-2 gap-1 ml-1">
                  {q.options.map((opt: string, optIdx: number) => (
                    <div
                      key={optIdx}
                      className="text-[10px] text-slate-600 flex items-baseline gap-0.5 min-w-0"
                    >
                      <span className="font-semibold shrink-0">
                        ({String.fromCharCode(97 + optIdx)})
                      </span>
                      <span className="break-words min-w-0">
                        <SafeMath>{opt}</SafeMath>
                      </span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      ))}
    </div>
  );

  return (
    <div className="w-full max-w-full overflow-x-hidden bg-slate-50 py-8 sm:py-12 px-4 sm:px-6 lg:px-8 text-slate-800 antialiased selection:bg-indigo-500 selection:text-white overflow-y-hidden">
      <div className="max-w-[2160px] mx-auto">
        <div className="mb-6">
          <h2 className="text-xl sm:text-2xl md:text-3xl font-black bg-linear-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent break-words">
            {title}
          </h2>
          <p className="text-sm md:text-base text-zinc-700 mt-1">
            {description}
          </p>
        </div>

        <div className="relative group/showcase">
          {canScrollLeft && (
            <button
              onClick={() => scroll("left")}
              className="hidden sm:flex absolute -left-3 top-1/2 -translate-y-1/2 z-20 w-8 h-8 rounded-full bg-white border border-slate-200 shadow-lg items-center justify-center text-slate-600 hover:text-indigo-600 hover:border-indigo-300 transition-all opacity-0 group-hover/showcase:opacity-100"
              aria-label="Scroll left"
            >
              <ChevronLeft />
            </button>
          )}

          <div
            ref={scrollRef}
            className="flex gap-3 sm:gap-4 overflow-x-auto scrollbar-hide scroll-smooth snap-x snap-mandatory pb-1"
            style={{ scrollbarWidth: "none", msOverflowStyle: "none" }}
          >
            {loading ? (
              Array.from({ length: 3 }).map((_, idx) => (
                <div
                  key={`skeleton-${idx}`}
                  className={`${CARD_WIDTH_CLASSES} bg-white rounded-2xl border border-slate-200/80 overflow-hidden shadow-md snap-start`}
                >
                  <div className="border-b border-slate-100 bg-slate-50/50 px-4 py-3">
                    <div className="h-4 w-32 bg-slate-200 rounded animate-pulse mb-2" />
                    <div className="h-3 w-48 bg-slate-200 rounded animate-pulse" />
                  </div>
                  <div className="p-4 space-y-3">
                    {Array.from({ length: 3 }).map((_, i) => (
                      <div key={i} className="space-y-2">
                        <div className="h-3 w-full bg-slate-200 rounded animate-pulse" />
                        <div className="h-3 w-3/4 bg-slate-200 rounded animate-pulse" />
                      </div>
                    ))}
                  </div>
                </div>
              ))
            ) : recentItems.length === 0 ? (
              <div
                className={`${CARD_WIDTH_CLASSES} bg-white rounded-2xl border border-slate-200/80 overflow-hidden shadow-md snap-start p-8 text-center text-slate-400`}
              >
                No recent items
              </div>
            ) : (
              recentItems.map((item, index) => (
                <motion.div
                  key={`${item.type}-${item._id}-${index}`}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: index * 0.1 }}
                  className={`${CARD_WIDTH_CLASSES} bg-white rounded-2xl border border-slate-200/80 overflow-hidden shadow-md snap-start`}
                >
                  <div className="border-b border-slate-100 bg-slate-50/50 px-4 py-3">
                    <div className="flex items-center justify-between gap-2 flex-wrap">
                      <h3 className="text-base font-bold text-slate-800 truncate min-w-0">
                        {item.type === "sample-paper"
                          ? "Sample Paper"
                          : "Subject Test"}
                      </h3>
                      <span
                        className={`text-[10px] font-extrabold px-2 py-0.5 rounded-full uppercase tracking-wider shrink-0 ${
                          item.type === "sample-paper"
                            ? "bg-emerald-50 text-emerald-600 border border-emerald-100"
                            : "bg-amber-50 text-amber-600 border border-amber-100"
                        }`}
                      >
                        {item.type === "sample-paper" ? "Paper" : "Test"}
                      </span>
                    </div>
                    <p className="text-xs text-slate-500 mt-1 truncate">
                      {item.class} •{" "}
                      {item.subject
                        ? item.subject.charAt(0).toUpperCase() +
                          item.subject.slice(1)
                        : ""}{" "}
                      • {item.exam_type}
                    </p>
                  </div>

                  <div className="max-h-[420px] overflow-y-auto overflow-x-hidden thin-scroll">
                    {item.type === "sample-paper"
                      ? renderSamplePaperPreview(item)
                      : renderSubjectTestPreview(item)}
                  </div>

                  <div className="border-t border-slate-100 bg-slate-50/30 px-4 py-2.5 flex justify-between items-center gap-2 flex-wrap">
                    <span className="text-xs text-slate-500 shrink-0">
                      {item.type === "sample-paper" && item.paperJson
                        ? `${
                            (item.paperJson.mcqs?.length || 0) +
                            (item.paperJson.subjective?.length || 0)
                          } questions`
                        : `${item.questions?.length || 0} questions`}
                    </span>
                    {/* <a
                      href={
                        item.type === "sample-paper"
                          ? `/sarthaks-ai/generate/${item._id}`
                          : `/public-test/${item._id}`
                      }
                      className="inline-flex items-center gap-1 text-xs font-medium text-indigo-600 hover:text-indigo-700 transition-colors shrink-0"
                    >
                      {item.type === "sample-paper"
                        ? "View Paper"
                        : "Attend Test"}
                      <svg
                        className="w-3.5 h-3.5"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2.5"
                        viewBox="0 0 24 24"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M9 5l7 7-7 7"
                        />
                      </svg>
                    </a> */}
                  </div>
                </motion.div>
              ))
            )}
          </div>

          {canScrollRight && (
            <button
              onClick={() => scroll("right")}
              className="hidden sm:flex absolute -right-3 top-1/2 -translate-y-1/2 z-20 w-8 h-8 rounded-full bg-white border border-slate-200 shadow-lg items-center justify-center text-slate-600 hover:text-indigo-600 hover:border-indigo-300 transition-all opacity-0 group-hover/showcase:opacity-100"
              aria-label="Scroll right"
            >
              <ChevronRight />
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

export default Showcase;
