"use client";

import Navigation from "./navigation/Navigation";
import HeroSection from "./sections/HeroSection";
import CoursesToolsSection from "./sections/CoursesToolsSection";
import CoursesSupported from "./sections/CoursesSupported";
import Showcase from "./sections/Showcase";
import SSRBox from "./SSRBox";
import LiveActivityTicker from "./sections/LiveActivityTicker";

const SarthaksAIExplore = () => {
  return (
    <SSRBox fallback={"Loading content..."}>
      {/* Fixed navigation bar */}
      <Navigation />

      {/* Page content starts below fixed nav (pt-16) */}
      <div className="pt-16">
        {/* ── Hero section ── */}
        <HeroSection />

        {/* ── Courses & Tools section ── */}
        <CoursesToolsSection />

        {/* ── Courses Supported section ── */}
        <CoursesSupported />

        {/* ── Recent Generated papers ── */}
        <Showcase
          filterType="all"
          title="RECENT GENERATED"
          description="Papers and tests generated by our students and teachers"
        />

        {/* ── Live Activity Ticker ── */}
        <LiveActivityTicker />
      </div>
    </SSRBox>
  );
};

export default SarthaksAIExplore;
