"use client";

import { useState } from "react";
import AICreditSection from "@/components/subscriptions/AICreditSection";
import Navigation, { NavSection } from "./navigation/Navigation";
import CoursesSupported from "./sections/CoursesSupported";
import Showcase, { RecentItemType } from "./sections/Showcase";
import SSRBox from "./SSRBox";
import QuickSetupFlow, { Selection } from "./sections/QuickSetupFlow";
import AIQuestionDemo from "./sections/AIQuestionDemo";
import SyllabusVisualizer from "./sections/SyllabusVisualizer";
import LiveActivityTicker from "./sections/LiveActivityTicker";
import { useRouter } from "next/navigation";

// Drives everything section-specific off one map: whether CoursesSupported
// shows, how deep QuickSetupFlow goes, and which Recent Generated bucket to
// filter to. Add a new nav tab by adding a row here.
interface SectionConfig {
  showCoursesSupported: boolean;
  /** QuickSetupFlow's `level` prop — undefined runs the full course→...→language chain (Explore). */
  quickSetupLevel?: "class" | "subject" | "chapter";
  quickSetupTitle: string;
  quickSetupDescription: string;
  /** Showcase's `filterType` — "all" shows everything (Explore). */
  recentType: RecentItemType | "all";
  recentTitle: string;
  recentDescription: string;
  /** Paper type value to auto-fill (undefined for "explore" which shows the step in the UI). */
  defaultPaperType?: string;
}

const SECTION_CONFIG: Record<NavSection, SectionConfig> = {
  explore: {
    showCoursesSupported: true,
    quickSetupLevel: undefined,
    quickSetupTitle: "QUICK SETUP",
    quickSetupDescription: "Choose your course and preferences to get started",
    recentType: "all",
    recentTitle: "RECENT GENERATED",
    recentDescription:
      "These papers and tests are generated by our students and teachers",
    defaultPaperType: undefined,
  },
  "sample-paper": {
    showCoursesSupported: false,
    quickSetupLevel: "subject",
    quickSetupTitle: "GENERATE A SAMPLE PAPER",
    quickSetupDescription:
      "Pick your course, subject, and chapter to generate a sample paper",
    recentType: "sample-paper",
    recentTitle: "RECENT SAMPLE PAPERS",
    recentDescription: "Sample papers generated by our students and teachers",
    defaultPaperType: "Sample Paper",
  },
  "subject-test": {
    showCoursesSupported: false,
    quickSetupLevel: "subject",
    quickSetupTitle: "GENERATE A SUBJECT TEST",
    quickSetupDescription:
      "Pick your course and subject to generate a full subject test",
    recentType: "subject-test",
    recentTitle: "RECENT SUBJECT TESTS",
    recentDescription: "Subject tests generated by our students and teachers",
    defaultPaperType: "Subject Test",
  },
  "full-syllabus": {
    showCoursesSupported: false,
    quickSetupLevel: "class",
    quickSetupTitle: "GENERATE A FULL SYLLABUS TEST",
    quickSetupDescription: "Pick your course to generate a full syllabus test",
    recentType: "full-syllabus-test",
    recentTitle: "RECENT FULL SYLLABUS TESTS",
    recentDescription:
      "Full syllabus tests generated by our students and teachers",
    defaultPaperType: "Full Syllabus Test",
  },
  "chapter-test": {
    showCoursesSupported: false,
    quickSetupLevel: "chapter",
    quickSetupTitle: "GENERATE A CHAPTER TEST",
    quickSetupDescription:
      "Pick your course, subject, and chapter to generate a chapter test",
    recentType: "chapter-test",
    recentTitle: "RECENT CHAPTER TESTS",
    recentDescription: "Chapter tests generated by our students and teachers",
    defaultPaperType: "Chapter Test",
  },
};

const SarthaksAIExplore = () => {
  const router = useRouter();
  const [activeSection, setActiveSection] = useState<NavSection>("explore");
  const cfg = SECTION_CONFIG[activeSection];

  const handleGenerate = (selection: Selection) => {
    const params = new URLSearchParams();
    // NOTE: ChatLayout's preload reads collectedData keyed "class" (matching
    // getNextStep's key_name), so this must be "class", not "course".
    if (selection.course) params.set("class", selection.course.trim());
    if (selection.subject) params.set("subject", selection.subject.trim());
    if (selection.chapter) params.set("chapter", selection.chapter.trim());
    if (selection.board) params.set("board", selection.board.trim());
    if (selection.paperType)
      params.set("paperType", selection.paperType.trim());
    if (selection.language) params.set("language", selection.language.trim());
    router.push(`/sarthaks-ai/generate/new?${params.toString()}`);
  };

  const isExplore = activeSection === "explore";

  return (
    <SSRBox fallback={"Loading content..."}>
      <Navigation
        activeSection={activeSection}
        onSectionChange={setActiveSection}
      />
      <div className="pt-16">
        {cfg.showCoursesSupported && <CoursesSupported />}

        {/* ── Interactive AI Demo (Explore only) ── */}
        {isExplore && <AIQuestionDemo />}

        {/* ── Syllabus Visualizer (Explore only) ── */}
        {isExplore && <SyllabusVisualizer />}

        <QuickSetupFlow
          key={activeSection}
          level={cfg.quickSetupLevel}
          defaultPaperType={cfg.defaultPaperType}
          title={cfg.quickSetupTitle}
          description={cfg.quickSetupDescription}
          onGenerate={handleGenerate}
        />
        <Showcase
          filterType={cfg.recentType}
          title={cfg.recentTitle}
          description={cfg.recentDescription}
        />

        {/* ── Live Activity Ticker (Explore only) ── */}
        {isExplore && <LiveActivityTicker />}

        {/* <div id="pricing-section" className="px-2 py-4 md:px-10 md:py-8 ">
          <AICreditSection courseKey="" disabled={false} />
        </div> */}
      </div>
    </SSRBox>
  );
};

export default SarthaksAIExplore;
